create table DiningHall(

DiningHallName VARCHAR(255) PRIMARY KEY,

Latitude REAL NOT NULL,

Longitude REAL NOT NULL

);

create table User(

NetID VARCHAR(255) NOT NULL PRIMARY KEY,

Name VARCHAR(255) NOT NULL

);

create table DiningHallTable(

TableID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

Capacity INT NOT NULL,

DiningHallName VARCHAR(255) NOT NULL,

FOREIGN KEY (DiningHallName) REFERENCES DiningHall(DiningHallName)

ON UPDATE CASCADE

ON DELETE CASCADE

);

create table QueueRequest(

QueueRequestID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

EnterQueueTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

ExitQueueTime TIMESTAMP NULL DEFAULT NULL,

RequestTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

Preferences VARCHAR(255) NULL,

Canceled BOOLEAN NOT NULL DEFAULT FALSE,

DiningHallName VARCHAR(255) NOT NULL,

FOREIGN KEY (DiningHallName) REFERENCES DiningHall(DiningHallName)

ON UPDATE CASCADE

ON DELETE CASCADE

);

create table AdmittedEntry(

EntryID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

MealType VARCHAR(255) NULL DEFAULT NULL,

AdmitOffQueueTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

GroupArrivalTime TIMESTAMP NULL DEFAULT NULL,

GroupExitTime TIMESTAMP NULL DEFAULT NULL,

TableID INT NOT NULL,

DiningHallName VARCHAR(255) NOT NULL,

QueueRequestID INT NOT NULL,

FOREIGN KEY (DiningHallName) REFERENCES DiningHall(DiningHallName),

FOREIGN KEY (TableID) REFERENCES DiningHallTable(TableID),

FOREIGN KEY (QueueRequestID) REFERENCES QueueRequest(QueueRequestID)

);

create table QueueGroup(

QueueRequestID INT NOT NULL,

NetID VARCHAR(255) NOT NULL,

FOREIGN KEY (QueueRequestID) REFERENCES QueueRequest(QueueRequestID),

FOREIGN KEY (NetID) REFERENCES User(NetID),

INDEX (QueueRequestID),

PRIMARY KEY (QueueRequestID, NetID)
);
